#!/bin/bash
def_dir=$PWD
IFS=$'\n'
if [ "$1" = "" ];then
	patch="/home/$USER/Downloads"
	echo "$patch"
else
	patch="$1"
	echo "$patch"
fi
clean1(){
if [ -d "/home/$USER/Downloads/" ];then
	cd "$patch"
	rename 'y/A-Z/a-z/' *
	## Music
	if [ -d Music ];then
		mv *.mp3 Music
	else
		mkdir Music
		mv *.mp3 Music
	fi
	## FILMS
	if [ -d Videos ];then
	        mv *.mp4 *.mkv *.webm Videos
	else
	        mkdir Videos
	        mv *.mp4 *.mkv *.webm Videos
	fi
	## Pdf
	if [ -d Pdf ];then
		mv *.pdf Pdf
	else
		mkdir Pdf
		mv *.pdf Pdf
	fi
	## picture
	if [ -d Pictures ];then
		mv *.jpg *.png *.svg Pictures
	else
		mkdir picture
		mv *.jpg *.png *.svg Pictures
	fi
	## archives
	if [ -d Archives ];then
		mv *.zip *.rar *.tar *.tar.* *.7z Archives
	else
		mkdir archive
		mv *.zip *.rar *.tar *.tar.* *.7z Archives
	fi
	## Texts
	if [ -d Text ];then
		mv *.txt Text
	else
		mkdir Text
		mv *.txt Text
	fi
	## Config Files
	if [ -d config ];then
		mv *.ini *.conf *.config config
	else
		mkdir config
		mv *.ini *.conf *.config config
	fi
	## Code
	if [ -d code ];then
		mv *.sh *.rb *.py *.php *.js *.html *.css *.cpp ## And Your Langs
	else
		mkdir code
		mv *.sh *.rb *.py *.php *.js *.html *.css *.cpp ## And Your Langs
	fi
	## others
	if [ -d Other ];then
		for file in * ;do test -f "$file" && mv "$file" Other ; done
	else
		mkdir other
		for file in * ;do test -f "$file" && mv "$file" Other ; done
	fi
	notify-send "$patch Is Clean!"
else
		notify-send "$patch Not Found, So This Is An ERROR!" 
fi
}
while true;do
	clean1 2>/dev/null
	rmdir * 2>/dev/null
	sleep 3600
done & >/dev/null
cd $def_dir
